version: "3.2"

services:
    php:
      build: 
        context: './php/'
      volumes:
        - ./www:/var/www/html/   
      container_name: dev-php
      restart: unless-stopped
    webserver:
      image: nginx:alpine
      container_name: dev-webserver
      restart: unless-stopped
      ports:
        - "8089:80"
      volumes:
        - ./www:/var/www/html/
        - ./site.conf:/etc/nginx/conf.d/default.conf